graphql:
  endpoint.url: https://api.github.com/graphql
  token: ${LANDSCAPE_SCANNING_TOKEN}
  
logging:
  level:
    org.springframework: DEBUG
    
debug: true
    

scan:
  landscapeUrl: https://raw.githubusercontent.com/finos/finos-landscape/master/landscape.yml
  orgs: 
    - finos
    - finos-labs
#  write-to:
#    type: file  
#    name: target/security-scorecard.csv


scanning2: 
  orgs: 
   - finos
   - finos-labs
  reports: readme, scan

scanning: 
  orgs: 
   - finos
   - finos-labs
  reports: readme, scan

readme:
  orgs: 
   - finos
   - finos-labs
  write-to:
    type: pr
    repo: project-analysis
    owner: finos-labs
    base: main
    head: generated-branch
