name: Landscape Scan Summarize

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * * "
    
env:
  LANDSCAPE_SCANNING_TOKEN: ${{ secrets.LANDSCAPE_SCANNING_TOKEN }}
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Run with Maven
      run: mvn spring-boot:run -Dspring-boot.run.profiles=pr -DskipTests
    - uses: actions/upload-artifact@v4
      with:
        name: Project-Report.csv
        path: target/toc-scorecard.csv
